fastblog/fastblog/models/__init__.py
from .post import Post
from .comment import Comment

fastblog/fastblog/models/comment.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse


class Comment(models.Model):

    post = models.ForeignKey('Post')

    user = models.ForeignKey(User)

    content = models.TextField()

    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return reverse(
                'fastblog:detail',
                kwargs={
                    'pk': self.post.id,
                }
        ) + '#comment-' + str(self.id)

fastblog/fastblog/models/post.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User


class PostManager(models.Manager):

    def public(self):
        return self.filter(is_public=True)


class Post(models.Model):

    objects = PostManager()

    user = models.ForeignKey(User)

    title = models.CharField(
            max_length=120,
    )

    content = models.TextField()

    image = models.ImageField(
            blank=True,
            null=True,
    )

    is_public = models.BooleanField(
            default=True,
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
                'fastblog:detail',
                kwargs={
                    'pk': self.id,
                }
        )

fastblog/bitly/views/create.py
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .base import BitLinkBaseView
from hashids import Hashids


class BitLinkCreateView(BitLinkBaseView, LoginRequiredMixin, CreateView):
    template_name = 'create.html'
    fields = [
        'original_url',
    ]
    success_url = '/mypage/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(BitLinkCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(BitLinkCreateView, self).get_context_data(**kwargs)
        context['site_name'] = 'Bitly'
        return context

fastblog/fastblog/settings/__init__.py
from .production import *

fastblog/fastblog/settings/partials/__init__.py
from .auth import *
from .base import *
from .database import *
from .internationalization import *
from .static import *

fastblog/fastblog/settings/partials/auth.py
# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL = "/login/"

fastblog/fastblog/urls/__init__.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from fastblog.views import *


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^', include('fastblog.urls.auth', namespace='auth')),

    url(r'^fastblog/', include('fastblog.urls.posts', namespace='fastblog')),

    url(r'^bitly/', include('fastblog.urls.bitly', namespace='bitly')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fastblog/fastblog/urls/auth.py
from django.conf.urls import url

from fastblog.views.auth import *


urlpatterns = [
    url(r'^signup/$', SignupView.as_view(), name='signup'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^mypage/$', MyPageView.as_view(), name='mypage'),
    url(r'^yourpage/(?P<user_name>\w+)/$', YourPageView.as_view(), name='yourpage'),

]

fastblog/fastblog/utils/__init__.py
from .slack import slack_notification
from .sms import send_sms

fastblog/fastblog/views/__init__.py
from .home import HomeView
from .auth import *

fastblog/fastblog/views/home.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['site_name'] = 'FastBlog Home'
        return context

fastblog/fastblog/views/posts/__init__.py
from .list import PostListView
from .detail import PostDetailView
from .create import PostCreateView
from .edit import PostEditView
from .delete import PostDeleteView
from .comments import *

fastblog/fastblog/views/posts/comments/__init__.py
from .comments_create import PostCommentCreateView
from .comments_edit import PostCommentEditView
from .comments_delete import PostCommentDeleteView

fastblog/fastblog/templates/posts/comment_edit.html
{% extends 'base.html' %}

{% block title %}{{ site_name }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1></br>
    <a href="{% url 'fastblog:edit' pk=post.id %}">Edit FastBlog Post</a></br>
    <a href="{% url 'fastblog:delete' pk=post.id %}">Delete FastBlog Post</a></br>
    <img src="{% if post.image %}{{ post.image.url }}{% else %}http://placehold.it/300x200{% endif %}" alt="{{ post.title }}">
    <p>{{ post.content }}</p>

    <h4>Comments ({{ post.comment_set.count }})</h4>
    <ul>
        {% for post_comment in post.comment_set.all %}
        {% if comment == post_comment %}
            <form action="" method="POST">
                {% csrf_token %} 
                <input type="text" name="content" value="{{ comment.content }}">
                <input type="submit" value="Edit">
            </form>
        {% else %}
            <li id="{{ post_comment.id }}">
                {{ post_comment.content }} 
                <a href="{% url 'fastblog:postcommentedit' pk=post.id comment_id=post_comment.id %}">Edit</a>
            </li>
        {% endif %}
        {% endfor %}
    </ul>

    <h4>Write a comment</h4>
    <form action="{% url 'fastblog:postcommentcreate' pk=post.id %}" method="POST">
        {% csrf_token %}
        <input type="text" name="content" placeholder="comment">
        <input type="submit">
    </form>
{% endblock %}

fastblog/fastblog/templates/posts/comments_edit.html
{% extends 'base.html' %}

{% block title %}{{ site_name }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1></br>
    <a href="{% url 'fastblog:edit' pk=post.id %}">Edit FastBlog Post</a></br>
    <a href="{% url 'fastblog:delete' pk=post.id %}">Delete FastBlog Post</a></br>
    <img src="{% if post.image %}{{ post.image.url }}{% else %}http://placehold.it/300x200{% endif %}" alt="{{ post.title }}">
    <p>{{ post.content }}</p>

    <h4>Comments ({{ post.comment_set.count }})</h4>
    <ul>
        {% for post_comment in post.comment_set.all %}
        {% if comment == post_comment %}
            <form action="" method="POST">
                {% csrf_token %} 
                <input type="text" name="content" value="{{ comment.content }}">
                <input type="submit" value="Edit">
            </form>
        {% else %}
            <li id="{{ post_comment.id }}">
                {{ post_comment.content }} 
                <a href="{% url 'fastblog:postcommentedit' pk=post.id comment_id=post_comment.id %}">Edit</a>
            </li>
        {% endif %}
        {% endfor %}
    </ul>

    <h4>Write a comment</h4>
    <form action="{% url 'fastblog:postcommentcreate' pk=post.id %}" method="POST">
        {% csrf_token %}
        <input type="text" name="content" placeholder="comment">
        <input type="submit">
    </form>
{% endblock %}

fastblog/fastblog/templates/posts/create.html
{% extends 'base.html' %}

{% block title %}{{ site_name }}{% endblock %}

{% block content %}
<h1>{{ site_name }}</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Publish">
</form>
{% endblock %}

fastblog/fastblog/templates/posts/delete_confirmation.html
{% extends 'base.html' %}

{% block title %}{{ site_name }}{% endblock %}

{% block content %}
<h1>{{ site_name }}</h1>
<form action="" method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete this post?</p>
    <input type="submit">
</form>
{% endblock %}

fastblog/fastblog/templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}{{ site_name }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1></br>
    <a href="{% url 'fastblog:edit' pk=post.id %}">Edit FastBlog Post</a></br>
    <a href="{% url 'fastblog:delete' pk=post.id %}">Delete FastBlog Post</a></br>
    <img src="{% if post.image %}{{ post.image.url }}{% else %}http://placehold.it/300x200{% endif %}" alt="{{ post.title }}">
    <p>{{ post.content }}</p>

    <h4>Comments ({{ post.comment_set.count }})</h4>
    <ul>
        {% for comment in post.comment_set.all %}
        <li id="{{ comment.id }}">
            {{ comment.content }} - written by {{ comment.user.username }}
            <a href="{% url 'fastblog:postcommentedit' pk=post.id comment_id=comment.id %}">Edit</a>
            <a href="{% url 'fastblog:postcommentdelete' pk=post.id comment_id=comment.id %}">Delete</a>
        </li>
        {% endfor %}
    </ul>

    <h4>Write a comment</h4>
    <form action="{% url 'fastblog:postcommentcreate' pk=post.id %}" method="POST">
        {% csrf_token %}
        <input type="text" name="content" placeholder="comment">
        <input type="submit">
    </form>
{% endblock %}

fastblog/fastblog/templates/posts/edit.html
{% extends 'base.html' %}

{% block title %}{{ site_name }}{% endblock %}

{% block content %}
<h1>{{ site_name }}</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
    
</form>
{% endblock %}

fastblog/fastblog/templates/posts/list.html
{% extends 'base.html' %}

{% block title %}{{ site_name }}{% endblock %}

{% block content %}
<h1>{{ site_name }}</h1>
<a href="{% url 'fastblog:create' %}">Create FastBlog</a>
<ul>
    {% for post in post_list %}
    <li>
        <h2><a href="{% url 'fastblog:detail' pk=post.id %}">{{ post.title }} ({{ post.comment_set.count }})</a></h2></br>
        <img src="{% if post.image %}{{ post.image.url }}{% else %}http://placehold.it/300x200{% endif %}" alt="{{ post.title }}">
        <p>{{ post.content }}</p>
        <p>:: posted by <a href="{% url 'auth:yourpage' user_name=post.user %}">@{{ post.user.username }}</a></p>
    </li>
    {% endfor %}
</ul>
{% endblock %}