fastblog/fastblog/models/__init__.py
from .post import Post
from .comment import Comment

fastblog/fastblog/models/comment.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse


class Comment(models.Model):

    post = models.ForeignKey('Post')

    user = models.ForeignKey(User)

    content = models.TextField()

    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return reverse(
                'fastblog:detail',
                kwargs={
                    'pk': self.post.id,
                }
        ) + '#comment-' + str(self.id)

fastblog/fastblog/models/post.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User


class PostManager(models.Manager):

    def public(self):
        return self.filter(is_public=True)


class Post(models.Model):

    objects = PostManager()

    user = models.ForeignKey(User)

    title = models.CharField(
            max_length=120,
    )

    content = models.TextField()

    image = models.ImageField(
            blank=True,
            null=True,
    )

    is_public = models.BooleanField(
            default=True,
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
                'fastblog:detail',
                kwargs={
                    'pk': self.id,
                }
        )

fastblog/bitly/views/base.py
from django.views.generic import View

from bitly.models import BitLink


class BitLinkBaseView(View):
    model = BitLink

fastblog/fastblog/settings/__init__.py
from .production import *

fastblog/fastblog/settings/partials/__init__.py
from .auth import *
from .base import *
from .database import *
from .internationalization import *
from .static import *

fastblog/fastblog/settings/partials/auth.py
# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL = "/login/"

fastblog/fastblog/urls/__init__.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from fastblog.views import *


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^', include('fastblog.urls.auth', namespace='auth')),

    url(r'^fastblog/', include('fastblog.urls.posts', namespace='fastblog')),

    url(r'^bitly/', include('fastblog.urls.bitly', namespace='bitly')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fastblog/fastblog/urls/auth.py
from django.conf.urls import url

from fastblog.views.auth import *


urlpatterns = [
    url(r'^signup/$', SignupView.as_view(), name='signup'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^mypage/$', MyPageView.as_view(), name='mypage'),
    url(r'^yourpage/(?P<user_name>\w+)/$', YourPageView.as_view(), name='yourpage'),

]

fastblog/fastblog/utils/__init__.py
from .slack import slack_notification
from .sms import send_sms

fastblog/fastblog/views/__init__.py
from .home import HomeView
from .auth import *

fastblog/fastblog/views/home.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['site_name'] = 'FastBlog Home'
        return context

fastblog/fastblog/views/posts/__init__.py
from .list import PostListView
from .detail import PostDetailView
from .create import PostCreateView
from .edit import PostEditView
from .delete import PostDeleteView
from .comments import *

fastblog/fastblog/views/posts/comments/__init__.py
from .comments_create import PostCommentCreateView
from .comments_edit import PostCommentEditView
from .comments_delete import PostCommentDeleteView

fastblog/fastblog/templates/base.html
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">

    <title>{% block title %}{% endblock %}</title>
    
</head>

<body>
    {% include 'header.html' %}
    {% block content %}
    {% endblock %}
    {% include 'footer.html' %}
</body>

fastblog/fastblog/templates/footer.html
<ul>
    <li><a href="{% url 'home' %}">Home</a></li>
</ul>

fastblog/fastblog/templates/header.html
<ul>
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'fastblog:list' %}">Blog</a></li>

    {% if request.user.is_authenticated %}
    <li><a href="{% url 'bitly:create' %}">Bitly</a></li>
    <li>Welcome, <a href="{% url 'auth:mypage' %}">@{{ request.user.username }}</a></li>
    <li><a href="{% url 'auth:logout' %}">Logout</a></li>
    {% else %}
    <li><a href="{% url 'auth:login' %}">Login</a></li>
    <li><a href="{% url 'auth:signup' %}">Signup</a></li>
    {% endif %}
</ul>

fastblog/fastblog/templates/home.html
{% extends 'base.html' %}

{% block title %}{{ site_name }}{% endblock %}

{% block content %}
<h1>{{ site_name }}</h1>
{% endblock %}